// User Roles
const ROLES = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  LIBRARIAN: 'LIBRARIAN',
  STAFF: 'STAFF',
  MEMBER: 'MEMBER'
};

// Permissions
const PERMISSIONS = {
  // User Management
  VIEW_USERS: 'view_users',
  CREATE_USER: 'create_user',
  EDIT_USER: 'edit_user',
  DELETE_USER: 'delete_user',
  MANAGE_ROLES: 'manage_roles',

  // Book Management
  VIEW_BOOKS: 'view_books',
  CREATE_BOOK: 'create_book',
  EDIT_BOOK: 'edit_book',
  DELETE_BOOK: 'delete_book',
  EXPORT_BOOKS: 'export_books',
  IMPORT_BOOKS: 'import_books',

  // Member Management
  VIEW_MEMBERS: 'view_members',
  CREATE_MEMBER: 'create_member',
  EDIT_MEMBER: 'edit_member',
  DELETE_MEMBER: 'delete_member',
  DEACTIVATE_MEMBER: 'deactivate_member',

  // Issue/Return
  VIEW_ISSUES: 'view_issues',
  CREATE_ISSUE: 'create_issue',
  VIEW_RETURNS: 'view_returns',
  CREATE_RETURN: 'create_return',

  // Renewals
  VIEW_RENEWALS: 'view_renewals',
  APPROVE_RENEWALS: 'approve_renewals',

  // Reservations
  VIEW_RESERVATIONS: 'view_reservations',
  APPROVE_RESERVATIONS: 'approve_reservations',

  // Fines
  VIEW_FINES: 'view_fines',
  MANAGE_FINES: 'manage_fines',
  ADJUST_FINES: 'adjust_fines',
  WAIVE_FINES: 'waive_fines',

  // Payments
  VIEW_PAYMENTS: 'view_payments',
  CREATE_PAYMENT: 'create_payment',
  MANAGE_PAYMENTS: 'manage_payments',

  // Reports
  VIEW_REPORTS: 'view_reports',
  EXPORT_REPORTS: 'export_reports',

  // Audit Logs
  VIEW_AUDIT_LOGS: 'view_audit_logs',

  // Settings
  MANAGE_SETTINGS: 'manage_settings',
  MANAGE_BACKUP: 'manage_backup',
  MANAGE_SECURITY: 'manage_security',

  // Dashboard
  VIEW_DASHBOARD: 'view_dashboard'
};

// Role-Permission Mapping
const ROLE_PERMISSIONS = {
  [ROLES.OWNER]: Object.values(PERMISSIONS), // All permissions
  
  [ROLES.ADMIN]: [
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.CREATE_USER,
    PERMISSIONS.EDIT_USER,
    PERMISSIONS.DEACTIVATE_MEMBER,
    PERMISSIONS.VIEW_BOOKS,
    PERMISSIONS.CREATE_BOOK,
    PERMISSIONS.EDIT_BOOK,
    PERMISSIONS.DELETE_BOOK,
    PERMISSIONS.EXPORT_BOOKS,
    PERMISSIONS.VIEW_MEMBERS,
    PERMISSIONS.CREATE_MEMBER,
    PERMISSIONS.EDIT_MEMBER,
    PERMISSIONS.VIEW_ISSUES,
    PERMISSIONS.CREATE_ISSUE,
    PERMISSIONS.VIEW_RETURNS,
    PERMISSIONS.CREATE_RETURN,
    PERMISSIONS.VIEW_RENEWALS,
    PERMISSIONS.APPROVE_RENEWALS,
    PERMISSIONS.VIEW_RESERVATIONS,
    PERMISSIONS.APPROVE_RESERVATIONS,
    PERMISSIONS.VIEW_FINES,
    PERMISSIONS.MANAGE_FINES,
    PERMISSIONS.ADJUST_FINES,
    PERMISSIONS.VIEW_PAYMENTS,
    PERMISSIONS.CREATE_PAYMENT,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EXPORT_REPORTS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.VIEW_DASHBOARD
  ],
  
  [ROLES.LIBRARIAN]: [
    PERMISSIONS.VIEW_BOOKS,
    PERMISSIONS.CREATE_BOOK,
    PERMISSIONS.EDIT_BOOK,
    PERMISSIONS.VIEW_MEMBERS,
    PERMISSIONS.CREATE_MEMBER,
    PERMISSIONS.EDIT_MEMBER,
    PERMISSIONS.VIEW_ISSUES,
    PERMISSIONS.CREATE_ISSUE,
    PERMISSIONS.VIEW_RETURNS,
    PERMISSIONS.CREATE_RETURN,
    PERMISSIONS.VIEW_RENEWALS,
    PERMISSIONS.APPROVE_RENEWALS,
    PERMISSIONS.VIEW_RESERVATIONS,
    PERMISSIONS.APPROVE_RESERVATIONS,
    PERMISSIONS.VIEW_FINES,
    PERMISSIONS.MANAGE_FINES,
    PERMISSIONS.VIEW_PAYMENTS,
    PERMISSIONS.CREATE_PAYMENT,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EXPORT_REPORTS,
    PERMISSIONS.VIEW_DASHBOARD
  ],
  
  [ROLES.STAFF]: [
    PERMISSIONS.VIEW_BOOKS,
    PERMISSIONS.VIEW_MEMBERS,
    PERMISSIONS.VIEW_ISSUES,
    PERMISSIONS.CREATE_ISSUE,
    PERMISSIONS.VIEW_RETURNS,
    PERMISSIONS.CREATE_RETURN,
    PERMISSIONS.VIEW_RENEWALS,
    PERMISSIONS.VIEW_RESERVATIONS,
    PERMISSIONS.VIEW_FINES,
    PERMISSIONS.VIEW_PAYMENTS,
    PERMISSIONS.CREATE_PAYMENT,
    PERMISSIONS.VIEW_DASHBOARD
  ],
  
  [ROLES.MEMBER]: [
    PERMISSIONS.VIEW_BOOKS,
    PERMISSIONS.VIEW_ISSUES,
    PERMISSIONS.VIEW_FINES,
    PERMISSIONS.VIEW_PAYMENTS
  ]
};

// Book Status
const BOOK_STATUS = {
  AVAILABLE: 'AVAILABLE',
  ISSUED: 'ISSUED',
  RESERVED: 'RESERVED',
  DAMAGED: 'DAMAGED',
  LOST: 'LOST',
  MAINTENANCE: 'MAINTENANCE'
};

// Issue Status
const ISSUE_STATUS = {
  ACTIVE: 'ACTIVE',
  RETURNED: 'RETURNED',
  OVERDUE: 'OVERDUE',
  LOST: 'LOST'
};

// Fine Status
const FINE_STATUS = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  WAIVED: 'WAIVED',
  CANCELLED: 'CANCELLED'
};

// Payment Status
const PAYMENT_STATUS = {
  COMPLETED: 'COMPLETED',
  PENDING: 'PENDING',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED'
};

// Reservation Status
const RESERVATION_STATUS = {
  PENDING: 'PENDING',
  AVAILABLE: 'AVAILABLE',
  FULFILLED: 'FULFILLED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED'
};

// Member Status
const MEMBER_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
  EXPIRED: 'EXPIRED'
};

// Audit Action Types
const AUDIT_ACTIONS = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  SOFT_DELETE: 'SOFT_DELETE',
  RESTORE: 'RESTORE',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  FAILED_LOGIN: 'FAILED_LOGIN',
  ROLE_CHANGE: 'ROLE_CHANGE',
  PERMISSION_CHANGE: 'PERMISSION_CHANGE',
  SETTINGS_CHANGE: 'SETTINGS_CHANGE',
  BACKUP_CREATED: 'BACKUP_CREATED',
  BACKUP_RESTORED: 'BACKUP_RESTORED'
};

module.exports = {
  ROLES,
  PERMISSIONS,
  ROLE_PERMISSIONS,
  BOOK_STATUS,
  ISSUE_STATUS,
  FINE_STATUS,
  PAYMENT_STATUS,
  RESERVATION_STATUS,
  MEMBER_STATUS,
  AUDIT_ACTIONS
};
